// Step19_ActiveXControl.idl: ActiveX 控件项目的类型库源。

// 此文件将由 MIDL 编译器工具处理以
// 生成类型库(Step19_ActiveXControl.tlb)，该类型库将成为
// Step19_ActiveXControl.ocx。

// 为了实现 COM 接口的二进制兼容，微软提供了 IDL 文件，这种文件采用独立的中间语言编写，IDL = 接口定义语言

#include <olectl.h>
#include <idispids.h>

[ uuid(05e6855b-e638-45d5-b798-8a7c6f17f183), version(1.0),control ]
library Step19ActiveXControlLib
{
	importlib(STDOLE_TLB);

	//  CStep19ActiveXControlCtrl 的主调度接口
	[ 
		uuid(5a3a3dca-965a-4d7b-ab92-d49ce81dea7d)
	]
	dispinterface _DStep19ActiveXControl
	{
		properties:
                [ id( DISPID_BACKCOLOR ), bindable, requestedit ] OLE_COLOR BackColor;	// Add
                [ id( DISPID_FORECOLOR ), bindable, requestedit ] OLE_COLOR ForeColor;	// Add

                [id( 1 )] LONG                                              Interval;	// (时间间隔) 自定义属性，该属性会显示在 IDE 的属性面板中
		methods:

			[id(DISPID_ABOUTBOX)] void AboutBox();
            [id( 2 )] void OnMouseClick( );	// 对应 CStep19ActiveXControlCtrl::OnClicked  两个可以不一致
	};

	//  CStep19ActiveXControlCtrl 的事件调度接口

	[ 
		uuid(daf4e232-181d-4a49-b011-2e079d55cbe6)
	]
	dispinterface _DStep19ActiveXControlEvents
	{
		properties:
			//  事件接口没有任何属性

		methods:
                [id( DISPID_KEYDOWN )] void KeyDown( SHORT * KeyCode, SHORT Shift );
                [id( 1 )] void              FireNewMinute( );
        };

	//  CStep19ActiveXControlCtrl 的类信息
	[
		uuid(ca2b8edd-562b-4e6c-b8e7-f0839397949c),
		control
	]
	coclass Step19ActiveXControl
	{
		[default] dispinterface _DStep19ActiveXControl;	// 属性和方法
		[default, source] dispinterface _DStep19ActiveXControlEvents;	// 事件
	};

	/**
	* 事件和属性/方法属于两个完全独立的接口，调度ID的数值可以相同，不会冲突；但是同一个接口内部，调度ID不能重复
	* !主调度接口存放属性和方法，用于给容器调用
	* !事件调度接口存放事件，是控件反向回调容器，容器中使用 EVENTSINK_MAP 声明事件接收器，在发生事件时，控件会调用容器实现的方法 (sink,接收器)
	*/

};
